version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - aws s3 cp s3://allwyn-demo-bucket/nvm.sh $HOME/nvm.sh
      - source s3://allwyn-demo-bucket/nvm.sh $HOME/nvm.sh
      - nvm install 14.17.0
      - npm install -g powershell
  build:
    commands:
      - powershell -File path/to/script.ps1
