version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | NVM_DIR="$HOME/.nvm" bash
      - export NVM_DIR="$HOME/.nvm"
	  - find / -name "nvm.sh"
      - source $C:\Users\Marek.litos\OneDrive - Adastra, s.r.o\Desktop\nvm.sh
      - nvm install 14.17.0
      - npm install -g powershell
  build:
    commands:
      - powershell -File path/to/script.ps1
