version: 0.2

phases:
  install:
    runtime-versions:
      powershell: 7.0
  build:
    commands:
      - powershell.exe -File test.ps1 | Out-File -FilePath random_output.txt -Encoding UTF8
artifacts:
  files:
    - random_output.txt

artifacts:
  files:
    - random_output.txt
  - AWS_ACCESS_KEY_ID: AKIAQDG5QCUMWENX2TT5
  - AWS_SECRET_ACCESS_KEY: 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
  - S3_BUCKET: mlprepare
