version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - nvm install 14.17.0
      - npm install -g powershell
  build:
    commands:
      - powershell -File path/to/script.ps1
