name: Allwyn-CI-Pipeline-to-AWS-S3
env:
  S3_BUCKET_NAME      : "mlprepare"
  AWS_REGION_NAME     : "eu-central-1"
  DEPLOY_PACKAGE_NAME : "data_${{ github.sha }}.zip"

on:
  push:
    branches: 
      - main
      
jobs:
  ci_part:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./src -x *-git*
      
    - name: Configure y AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{secrets.ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
        aws-region           : ${{env.AWS_REGION_NAME}}
        
    - name: Copy data to S3
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.S3_BUCKET_NAME }}/
